#!/usr/bin/env python3
"""Governed Cognitive Matrix contract generator.

Origin architect / steward: Trang Phan.

This generator fills only placeholder or generator-owned contract surfaces. It
never treats generated prose as implementation, validation, authority, canon, or
mathematical proof. Numeric package order is identity only: it is not dependency,
causality, temporal order, or execution order.
"""
from __future__ import annotations

import argparse
import datetime as _dt
import json
import os
from pathlib import Path
import re
import tempfile
from typing import Dict, Iterable, Mapping, Tuple

ROOT = Path(__file__).resolve().parent.parent
GENERATOR_VERSION = "2.0.0"
GENERATED_MARKER = "**Generated by:** governed `fill_matrix.py`"
PLACEHOLDER_MARKER = "PLACEHOLDER / UNVALIDATED"

FTYPE_MAP = {
    "DEFINITION": "Definition",
    "PURPOSE": "Purpose",
    "SEMANTICS": "Semantics",
    "INPUT_OUTPUT": "Input/Output",
    "PRECONDITIONS": "Preconditions",
    "POSTCONDITIONS": "Postconditions",
    "STATE_TRANSITIONS": "State Transitions",
    "INVARIANTS": "Invariants",
    "FAILURE_MODES": "Failure Modes",
    "REPAIR": "Repair & Recovery",
    "DEPENDENCIES": "Dependencies",
    "CONTROL_PLANES": "Control-Plane Requirements",
    "AGENTS": "Agents",
    "SKILLS": "Skills",
    "WORKFLOWS": "Workflows",
    "PROTOCOLS": "Protocols",
    "TESTS": "Tests & Validators",
    "GAP_MATRIX": "Gap Matrix",
    "PROVENANCE": "Provenance",
    "RSCF": "RSCF Record",
    "HML": "H/M/L Applicability",
    "MEMORY": "Memory Contract",
    "EQUATIONS": "Equations",
    "VARIABLES": "Variables",
    "OPERATORS": "Operators",
    "STATE": "State",
    "README": "Overview",
    "AUTHORITY": "Authority",
    "SCOPE": "Scope",
    "POLICIES": "Policies",
    "DECISION_RULES": "Decision Rules",
    "OBSERVABILITY": "Observability",
    "BOUNDARIES": "Boundaries",
    "TRANSLATION_RULES": "Translation Rules",
}

PROTECTED_RUNTIME_MARKERS = (
    "IMPLEMENTED / VALIDATED_BOUNDED",
    "EXECUTABLE_BOUNDED",
    "VALIDATED_BOUNDED",
    "CURRENT BOUNDED EXECUTABLE",
    "Current bounded executable",
)

GLOBAL_HARD_BOUNDARIES = (
    "CONTRACT_FILLED != IMPLEMENTED",
    "DOCUMENTED != EXECUTABLE",
    "MODEL != VERIFIED",
    "UNKNOWN/GAP != PASS",
    "PACKAGE_NUMBERING != DEPENDENCY",
    "PACKAGE_NUMBERING != CAUSALITY",
    "CAPABILITY != AUTHORITY",
    "PROPOSAL != COMMIT",
    "INDEXED_FIELD != ALGEBRAIC_TENSOR",
    "STRUCTURAL_ADJACENCY != POINT_SET_TOPOLOGY",
)

FORBIDDEN_GENERATED_ASSERTIONS = (
    "Dependency direction follows the primitive flow order",
    "confidence_ceiling: 0.6",
)


def _parse_args(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--force",
        action="store_true",
        help="Refill generator-owned contract files only; runtime-bound repairs remain protected.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Compute the fill receipt without writing files.",
    )
    return parser.parse_args(argv)


def ftype_of(fname: str):
    base = fname.removesuffix(".md")
    for key in sorted(FTYPE_MAP, key=len, reverse=True):
        if base.endswith("_" + key):
            return key
    return None


def load_payloads() -> Dict[str, dict]:
    import payloads_a
    import payloads_b
    import payloads_c1
    import payloads_c2
    import payloads_d1
    import payloads_d2
    import payloads_e
    import payloads_f

    payloads: Dict[str, dict] = {}
    for module in (
        payloads_a,
        payloads_b,
        payloads_c1,
        payloads_c2,
        payloads_d1,
        payloads_d2,
        payloads_e,
        payloads_f,
    ):
        for key, value in module.PAYLOADS.items():
            if key in payloads and payloads[key] != value:
                raise ValueError(f"payload identity collision: {key}")
            payloads[key] = value
    return payloads


def validate_payload(payload_id: str, payload: Mapping[str, object]) -> None:
    required = {
        "definition",
        "scope",
        "purpose",
        "semantics",
        "inputs",
        "outputs",
        "preconditions",
        "postconditions",
        "state_vars",
        "transitions",
        "invariants",
        "failure_modes",
        "recovery",
        "deps_up",
        "deps_down",
        "control_planes",
        "cp_roles",
        "agents",
        "skills",
        "workflows",
        "protocols",
        "tests",
        "hml",
        "state_ownership",
        "variables",
        "operators",
        "equations",
        "memory",
        "authority",
        "observability",
        "translation_rules",
    }
    missing = sorted(required - set(payload))
    if missing:
        raise ValueError(f"payload {payload_id} missing keys: {missing}")
    for key in ("definition", "scope"):
        value = payload[key]
        if not isinstance(value, str) or not value.strip():
            raise ValueError(f"payload {payload_id} requires non-empty {key}")


def should_fill(text: str, *, force: bool) -> bool:
    """Protect manually/runtime-repaired files from generator rollback.

    Normal mode fills declared placeholders only. Force mode may additionally
    refill files that this generator itself owns, but never a runtime-bound file.
    """
    if any(marker in text for marker in PROTECTED_RUNTIME_MARKERS):
        return False
    if PLACEHOLDER_MARKER in text:
        return True
    if force and GENERATED_MARKER in text:
        return True
    return False


def _lines(items: Iterable[object]) -> list[str]:
    return [f"- {item}" for item in items]


def _append_section(lines: list[str], title: str, body: Iterable[str] | str) -> None:
    lines.extend(("", f"## {title}", ""))
    if isinstance(body, str):
        lines.append(body)
    else:
        lines.extend(body)


def build_body(
    pkg_id: str,
    pkg_name: str,
    family: str,
    ftype: str,
    payload: Mapping[str, object],
    fname: str,
) -> str:
    validate_payload(pkg_id, payload)
    title = FTYPE_MAP.get(ftype, ftype.title())
    definition = str(payload["definition"])
    lines: list[str] = [
        f"# {pkg_id} — {title}",
        "",
        f"**Package:** `{pkg_id}_{pkg_name}`  ",
        "**Class:** `COGNITIVE_MATRIX_CONTRACT`  ",
        "**Epistemic class:** `DERIVED / AMOS_MODEL`  ",
        "**Status:** `CONTRACT_FILLED / IMPLEMENTATION_NOT_INFERRED / VALIDATION_NOT_INFERRED`  ",
        f"{GENERATED_MARKER} · **Version:** `{GENERATOR_VERSION}`",
    ]
    _append_section(lines, "Scope", str(payload["scope"]))

    if ftype == "DEFINITION":
        _append_section(lines, "Definition", definition)
        lines.append("This is a contract-level definition, not an implementation or validation claim.")
    elif ftype == "PURPOSE":
        _append_section(lines, "Purpose", (definition.split(". ")[0] + ".", str(payload["purpose"])))
    elif ftype == "SEMANTICS":
        _append_section(lines, "Semantics", definition)
        _append_section(lines, "Semantic rules", _lines(payload["semantics"]))
    elif ftype == "INPUT_OUTPUT":
        _append_section(lines, "Typed inputs", _lines(payload["inputs"]))
        _append_section(lines, "Typed outputs", _lines(payload["outputs"]))
    elif ftype == "PRECONDITIONS":
        _append_section(lines, "Preconditions", _lines(payload["preconditions"]))
    elif ftype == "POSTCONDITIONS":
        _append_section(lines, "Postconditions", _lines(payload["postconditions"]))
    elif ftype == "STATE_TRANSITIONS":
        _append_section(lines, "State variables", _lines(payload["state_vars"]))
        _append_section(lines, "Transitions", _lines(payload["transitions"]))
    elif ftype == "INVARIANTS":
        body = [f"- `INV-{pkg_id}-{item[0]}`: {item[1]}" for item in payload["invariants"]]
        _append_section(lines, "Invariants", body)
    elif ftype == "FAILURE_MODES":
        body = [
            f"- `FM-{pkg_id}-{item[0]}`: {item[1]} -> detection: {item[2]}"
            for item in payload["failure_modes"]
        ]
        _append_section(lines, "Failure modes", body)
    elif ftype == "REPAIR":
        body = [f"- On `FM-{pkg_id}-{item[0]}`: {item[3]}" for item in payload["failure_modes"]]
        _append_section(lines, "Failure handling", body)
        _append_section(lines, "Recovery basin", str(payload["recovery"]))
    elif ftype == "DEPENDENCIES":
        _append_section(lines, "Upstream dependencies", _lines(f"[[{dep}]]" for dep in payload["deps_up"]))
        _append_section(lines, "Downstream dependents", _lines(f"[[{dep}]]" for dep in payload["deps_down"]))
        lines.extend(
            (
                "",
                "Only explicitly declared payload dependencies are emitted.",
                "Numeric or lexical package order is not dependency, causality, temporal order, or execution order.",
                "Cycle admissibility is dependency-kind and control-policy specific; cycles are not rejected merely by shape.",
            )
        )
    elif ftype == "CONTROL_PLANES":
        body = []
        roles = payload["cp_roles"]
        for control_plane in payload["control_planes"]:
            body.append(f"- [[{control_plane}]] — {roles.get(control_plane, 'bound control plane')}")
        _append_section(lines, "Control-plane binding", body)
    elif ftype == "AGENTS":
        _append_section(lines, "Agent requirements", _lines(payload["agents"]))
        lines.append("Generator output does not prove a runtime agent binding; authoritative registries own that status.")
    elif ftype == "SKILLS":
        _append_section(lines, "Governing skills", _lines(payload["skills"]))
    elif ftype == "WORKFLOWS":
        _append_section(lines, "Workflow requirements", _lines(payload["workflows"]))
    elif ftype == "PROTOCOLS":
        _append_section(lines, "Protocol surface", _lines(payload["protocols"]))
    elif ftype == "TESTS":
        body = [f"- `T-{pkg_id}-{i:03d}`: {test} — status `DEFINED`" for i, test in enumerate(payload["tests"], 1)]
        _append_section(lines, "Defined tests (TEST_DEFINED != TEST_EXECUTED)", body)
        lines.append("Execution status must be bound from a separate validator/CI receipt; this generator never fabricates it.")
    elif ftype == "GAP_MATRIX":
        _append_section(
            lines,
            "Gap matrix",
            (
                "| Surface | Generator status |",
                "|---|---|",
                "| Definition/contract | FILLED |",
                "| Executable implementation | NOT INFERRED |",
                "| Validation evidence | NOT INFERRED |",
                "| Authority binding | NOT INFERRED |",
                "| Runtime integration | NOT INFERRED |",
            ),
        )
    elif ftype == "PROVENANCE":
        _append_section(
            lines,
            "Provenance",
            (
                "- Source class: `DERIVED / AMOS_MODEL` — reconstructed from declared AMOS payloads",
                f"- Generator: `fill_matrix.py` version `{GENERATOR_VERSION}`",
                "- Generated content does not become SOURCE_CLAIM, implementation evidence, or Canon by generation.",
            ),
        )
    elif ftype == "RSCF":
        _append_section(
            lines,
            "RSCF record",
            (
                "```yaml",
                "claim_class: AMOS_MODEL",
                "evidence: []",
                "provenance:",
                "  - AMOS generated contract payload",
                "scope: cognitive_matrix_package_contract",
                "regime: architecture-contract",
                "dependencies: " + json.dumps(list(payload["deps_up"])),
                "competing: []",
                "falsifiers:",
                "  - authoritative_source_contradiction",
                "  - executed_evidence_contradiction",
                "confidence_ceiling: UNCALIBRATED",
                "```",
            ),
        )
        lines.append("No numerical confidence is minted by the generator without a calibration model.")
    elif ftype == "HML":
        hml = payload["hml"]
        _append_section(
            lines,
            "H/M/L applicability",
            (
                "| Scale | Applicability |",
                "|---|---|",
                f"| H | {hml['H']} |",
                f"| M | {hml['M']} |",
                f"| L | {hml['L']} |",
            ),
        )
        lines.append("Cross-scale similarity is not mechanism identity, equivalence, or causality.")
    else:
        _append_section(lines, "Contract content", definition)
        extras = {
            "STATE": ("State ownership", str(payload["state_ownership"])),
            "VARIABLES": ("Core variables", _lines(payload["variables"])),
            "OPERATORS": ("Operators exposed", _lines(payload["operators"])),
            "EQUATIONS": ("Equations", str(payload["equations"])),
            "MEMORY": ("Memory interaction", str(payload["memory"])),
            "AUTHORITY": ("Authority requirements", str(payload["authority"])),
            "OBSERVABILITY": ("Observability signals", str(payload["observability"])),
            "TRANSLATION_RULES": ("Translation rules", str(payload["translation_rules"])),
        }
        if ftype in extras:
            heading, body = extras[ftype]
            _append_section(lines, heading, body)
        elif ftype == "README":
            _append_section(
                lines,
                "Package inventory",
                f"`{pkg_id}_{pkg_name}` is a declared {family} package. Generated contract coverage does not determine implementation or validation maturity.",
            )
        elif ftype == "BOUNDARIES":
            _append_section(
                lines,
                "Boundaries",
                (
                    "```text",
                    "PACKAGE_SEEDED != PACKAGE_COMPLETE",
                    "CONTRACT != IMPLEMENTATION",
                    "IMPLEMENTATION != VALIDATION",
                    "UNKNOWN/GAP != PASS",
                    "```",
                ),
            )
        elif ftype in ("POLICIES", "DECISION_RULES"):
            _append_section(lines, "Rules", (f"- Enforce: {item[1]}" for item in payload["invariants"]))

    if ftype == "EQUATIONS":
        lines.extend(
            (
                "",
                "Generated equation text remains `DERIVED / AMOS_MODEL` unless an exact source equation or executed/formal proof receipt is separately bound.",
            )
        )

    _append_section(lines, "Hard boundaries", ("```text", *GLOBAL_HARD_BOUNDARIES, "```"))
    lines.extend(
        (
            "",
            "---",
            "[[COGNITIVE_MATRIX_MOC]] · [[00_ROOT/00_ROOT_MOC.md|AMOS MOC]]",
            "",
            "---",
            "RSCF-NODE",
            f"node_id: {pkg_id.lower()}_{family.split('_')[-1].lower()}_{ftype.lower()}".replace("scale_", ""),
            "node_type: note",
            f"path: {family}/{pkg_id}_{pkg_name}/{fname}",
            "claim_class: AMOS_MODEL",
        )
    )
    rendered = "\n".join(lines).rstrip() + "\n"
    validate_rendered_output(rendered)
    return rendered


def validate_rendered_output(text: str) -> None:
    for forbidden in FORBIDDEN_GENERATED_ASSERTIONS:
        if forbidden in text:
            raise ValueError(f"forbidden generated assertion: {forbidden}")
    for boundary in GLOBAL_HARD_BOUNDARIES:
        if boundary not in text:
            raise ValueError(f"generated output missing hard boundary: {boundary}")
    if "claim_class: SOURCE_CLAIM" in text:
        raise ValueError("generator may not mint SOURCE_CLAIM")


def _atomic_write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile("w", encoding="utf-8", dir=path.parent, delete=False) as handle:
        handle.write(text)
        temp_name = handle.name
    os.replace(temp_name, path)


def _package_key(pkg_id: str, payloads: Mapping[str, dict]):
    if pkg_id in payloads:
        return pkg_id
    scale_key = "SCALE_" + pkg_id
    if pkg_id in "HML" and scale_key in payloads:
        return scale_key
    return None


def main(argv=None) -> int:
    args = _parse_args(argv)
    payloads = load_payloads()
    for payload_id, payload in payloads.items():
        validate_payload(payload_id, payload)

    receipt = {
        "generated_at_utc": _dt.datetime.now(_dt.timezone.utc).isoformat(),
        "generator": "25_COGNITIVE_MATRIX/12_GENERATORS/fill_matrix.py",
        "generator_version": GENERATOR_VERSION,
        "dry_run": args.dry_run,
        "force": args.force,
        "filled": 0,
        "skipped": 0,
        "protected_runtime_bound": 0,
        "packages_without_payload": 0,
        "by_family": {},
        "infra_filled": 0,
        "status": "CONTRACT_FILL_BOUNDED",
        "boundaries": list(GLOBAL_HARD_BOUNDARIES),
    }

    for family in ("01_PRIMITIVES", "02_LIFECYCLE_OPERATIONS", "03_CONTROL_PLANES", "04_SCALES"):
        family_dir = ROOT / family
        if not family_dir.is_dir():
            continue
        for package_dir in sorted(p for p in family_dir.iterdir() if p.is_dir() and p.name != "00_INDEX"):
            match = re.match(r"(L\d+|O\d+|C\d+|[HML])_(.+)", package_dir.name)
            if not match:
                continue
            pkg_id, pkg_name = match.group(1), match.group(2)
            key = _package_key(pkg_id, payloads)
            if key is None:
                receipt["packages_without_payload"] += 1
                continue
            payload = payloads[key]
            for path in sorted(package_dir.glob("*.md")):
                if path.name.startswith("COGNITIVE_MATRIX_" + pkg_id) or "_00_INDEX" in path.name:
                    continue
                ftype = ftype_of(path.name)
                if ftype is None:
                    continue
                text = path.read_text(encoding="utf-8")
                if any(marker in text for marker in PROTECTED_RUNTIME_MARKERS):
                    receipt["protected_runtime_bound"] += 1
                    continue
                if not should_fill(text, force=args.force):
                    receipt["skipped"] += 1
                    continue
                rendered = build_body(pkg_id, pkg_name, family, ftype, payload, path.name)
                if not args.dry_run:
                    _atomic_write(path, rendered)
                receipt["filled"] += 1
                receipt["by_family"][family] = receipt["by_family"].get(family, 0) + 1

    infra_dirs = (
        "05_CELL_REGISTRY",
        "06_CELL_CONTRACTS",
        "07_COVERAGE",
        "08_STRUCTURAL_GAPS",
        "09_DEPENDENCY_GRAPH",
        "10_ROUTING",
        "11_VALIDATION",
    )
    stem_keys = {
        "CELL_INDEX": "CELL_INDEX",
        "CELL_STATUS_REGISTRY": "CELL_STATUS_REGISTRY",
        "CELL_AUTHORITY": "CELL_AUTHORITY",
        "CELL_BINDINGS": "CELL_BINDINGS",
        "CELL_EVIDENCE": "CELL_EVIDENCE",
        "CELL_STATE": "CELL_STATE",
        "COVERAGE_THRESHOLDS": "COVERAGE_THRESHOLDS",
        "COVERAGE_AUDIT": "COVERAGE_AUDIT",
        "COVERAGE_MODEL": "COVERAGE_MODEL",
        "GAP_PRIORITY": "GAP_PRIORITY",
        "GAP_REGISTRY": "GAP_REGISTRY",
        "GAP_PROMOTION": "GAP_PROMOTION",
        "DEPENDENCY_TYPES": "DEPENDENCY_TYPES",
        "INVALIDATION_RULES": "INVALIDATION_RULES",
        "DEPENDENCY_AUDIT": "DEPENDENCY_AUDIT",
        "ROUTING_POLICY": "ROUTING_POLICY",
        "BINDING_RULES": "BINDING_RULES",
        "ROUTING_AUDIT": "ROUTING_AUDIT",
    }
    for directory in infra_dirs:
        base = ROOT / directory
        if not base.is_dir():
            continue
        for path in sorted(base.glob("*.md")):
            key = stem_keys.get(path.stem.upper())
            if key is None or key not in payloads:
                continue
            text = path.read_text(encoding="utf-8")
            if any(marker in text for marker in PROTECTED_RUNTIME_MARKERS):
                receipt["protected_runtime_bound"] += 1
                continue
            if not should_fill(text, force=args.force):
                receipt["skipped"] += 1
                continue
            rendered = build_body(key, "", directory, "DEFINITION", payloads[key], path.name)
            if not args.dry_run:
                _atomic_write(path, rendered)
            receipt["infra_filled"] += 1

    print(json.dumps(receipt, indent=2, sort_keys=True))
    if not args.dry_run:
        _atomic_write(ROOT / "07_COVERAGE" / "FILL_RECEIPT.json", json.dumps(receipt, indent=2, sort_keys=True) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
