---
title: O14 Action MOC
type: moc
source: 25_COGNITIVE_MATRIX/02_LIFECYCLE_OPERATIONS/O14_ACTION
tags:
- o14-action
- domain/cognitive-matrix
- cognitive-matrix-o14-action-contract
- 00-index-moc
- 02-lifecycle-operations-moc
rscf:
  state: DERIVED
  claim_class: DERIVED
  provenance: AMOS_corpus
  scope: AMOS_general
---

# O14 Action — Map of Content

**Path:** `25_COGNITIVE_MATRIX/02_LIFECYCLE_OPERATIONS/O14_ACTION`
**Files:** 20 | **Subdirectories:** 1

## Files

- [[COGNITIVE_MATRIX_O14_ACTION_CONTRACT]]
- [[O14_ACTION_LIFECYCLE_OPERATIONS_COGNITIVE_MATRIX_AGENTS]]
- [[O14_ACTION_LIFECYCLE_OPERATIONS_COGNITIVE_MATRIX_CONTROL_PLANES]]
- [[O14_ACTION_LIFECYCLE_OPERATIONS_COGNITIVE_MATRIX_DEFINITION]]
- [[O14_ACTION_LIFECYCLE_OPERATIONS_COGNITIVE_MATRIX_DEPENDENCIES]]
- [[O14_ACTION_LIFECYCLE_OPERATIONS_COGNITIVE_MATRIX_FAILURE_MODES]]
- [[O14_ACTION_LIFECYCLE_OPERATIONS_COGNITIVE_MATRIX_GAP_MATRIX]]
- [[O14_ACTION_LIFECYCLE_OPERATIONS_COGNITIVE_MATRIX_HML]]
- [[O14_ACTION_LIFECYCLE_OPERATIONS_COGNITIVE_MATRIX_INPUT_OUTPUT]]
- [[O14_ACTION_LIFECYCLE_OPERATIONS_COGNITIVE_MATRIX_INVARIANTS]]
- [[O14_ACTION_LIFECYCLE_OPERATIONS_COGNITIVE_MATRIX_POSTCONDITIONS]]
- [[O14_ACTION_LIFECYCLE_OPERATIONS_COGNITIVE_MATRIX_PRECONDITIONS]]
- [[O14_ACTION_LIFECYCLE_OPERATIONS_COGNITIVE_MATRIX_PROTOCOLS]]
- [[O14_ACTION_LIFECYCLE_OPERATIONS_COGNITIVE_MATRIX_README]]
- [[O14_ACTION_LIFECYCLE_OPERATIONS_COGNITIVE_MATRIX_RSCF]]
- [[O14_ACTION_LIFECYCLE_OPERATIONS_COGNITIVE_MATRIX_SEMANTICS]]
- [[O14_ACTION_LIFECYCLE_OPERATIONS_COGNITIVE_MATRIX_SKILLS]]
- [[O14_ACTION_LIFECYCLE_OPERATIONS_COGNITIVE_MATRIX_STATE_TRANSITIONS]]
- [[O14_ACTION_LIFECYCLE_OPERATIONS_COGNITIVE_MATRIX_TESTS]]
- [[O14_ACTION_LIFECYCLE_OPERATIONS_COGNITIVE_MATRIX_WORKFLOWS]]

## Subdirectories

- [[00_INDEX_MOC]] — 00_INDEX

---
**Parent:** [[02_LIFECYCLE_OPERATIONS_MOC]]
