#!/usr/bin/env python3
"""
skill_catalog_generator.py — Auto-generate a browsable skill catalog from frontmatter.

Inspired by SOTA repos:
  - event4u-app/agent-config: auto-generated skills-catalog.md from SKILL.md frontmatter
  - mianbaofang/agent-skill-catalog: local skill catalog, parent-child families, classification
  - microsoft/agent-skills: Skill Explorer with 1-click install, language-based plugins
  - kimduhee7524/readme-generator: deterministic 6-step workflow, scan + build + validate

This tool:
  1. Scans all SKILL.md frontmatter across the vault
  2. Groups skills by domain, parent-child relationships
  3. Generates a browsable Markdown catalog with clickable links
  4. Generates a JSON index for programmatic access
  5. Validates catalog against actual skill directories

Usage:
  python3 scripts/skill_catalog_generator.py [--skills-dir DIR] [--output FILE]
  python3 scripts/skill_catalog_generator.py --skills-dir DIR --json FILE
"""

import argparse
import json
import re
import sys
from pathlib import Path
from datetime import datetime, timezone
from typing import Dict, List, Optional
from collections import defaultdict


def parse_frontmatter(content: str) -> dict:
    """Parse YAML frontmatter from markdown content."""
    fm = {}
    match = re.match(r'^---\n(.*?)\n---', content, re.DOTALL)
    if not match:
        return fm
    fm_text = match.group(1)
    for line in fm_text.split('\n'):
        if ':' in line:
            key, _, value = line.partition(':')
            key = key.strip()
            value = value.strip().strip('"').strip("'")
            if value:
                fm[key] = value
    return fm


def extract_catalog_entry(skill_dir: Path, base_path: Path) -> dict:
    """Extract a catalog entry from a skill directory."""
    skill_md = skill_dir / "SKILL.md"
    if not skill_md.exists():
        return {}

    content = skill_md.read_text(encoding="utf-8")
    fm = parse_frontmatter(content)

    # Extract description (truncate for catalog)
    description = fm.get("description", "")
    if len(description) > 120:
        description = description[:117] + "..."

    # Build relative path for links
    rel_path = skill_dir.relative_to(base_path)

    # Count sections and capabilities
    sections = re.findall(r'^##\s+(.+)$', content, re.MULTILINE)
    cap_count = len(re.findall(r'^-\s+\*\*.+?\*\*', content, re.MULTILINE))

    # File count
    files = list(skill_dir.rglob("*"))
    file_count = sum(1 for f in files if f.is_file())

    return {
        "name": skill_dir.name,
        "title": fm.get("title", skill_dir.name),
        "description": description,
        "domain": fm.get("domain", ""),
        "parent_skill": fm.get("parent_skill", "none"),
        "epistemic_class": fm.get("epistemic_class", ""),
        "version": fm.get("version", "1.0.0"),
        "origin_architect": fm.get("origin_architect", ""),
        "path": str(rel_path),
        "section_count": len(sections),
        "capability_count": cap_count,
        "file_count": file_count,
        "sections": sections,
    }


def build_catalog(skills_dir: Path) -> dict:
    """Build complete catalog from all skills."""
    entries = []
    domain_map = defaultdict(list)
    parent_children = defaultdict(list)

    for d in sorted(skills_dir.iterdir()):
        if not (d.is_dir() and (d / "SKILL.md").exists()):
            continue

        entry = extract_catalog_entry(d, skills_dir)
        if not entry:
            continue

        entries.append(entry)
        domain = entry.get("domain", "unknown")
        domain_map[domain].append(entry["name"])

        parent = entry.get("parent_skill", "none")
        if parent and parent != "none":
            parent_children[parent].append(entry["name"])

    # Sort domain map
    sorted_domains = {}
    for domain in sorted(domain_map):
        sorted_domains[domain] = sorted(domain_map[domain])

    # Sort parent-children map
    sorted_parents = {}
    for parent in sorted(parent_children):
        sorted_parents[parent] = sorted(parent_children[parent])

    return {
        "generated": datetime.now(timezone.utc).isoformat(),
        "total_skills": len(entries),
        "total_domains": len(sorted_domains),
        "total_parents": len(sorted_parents),
        "domains": sorted_domains,
        "parent_children": sorted_parents,
        "skills": entries,
    }


def generate_catalog_markdown(catalog: dict, skills_dir: Path) -> str:
    """Generate a browsable Markdown catalog."""
    lines = [
        f"<!-- Auto-generated by skill_catalog_generator.py — do not edit manually -->",
        f"<!-- Regenerate: python3 scripts/skill_catalog_generator.py --skills-dir {skills_dir} -->",
        "",
        "# AMOS Skill Catalog",
        "",
        f"> **{catalog['total_skills']} skills** across **{catalog['total_domains']} domains**",
        f"> Generated: {catalog['generated']}",
        "",
        "## Domain Index",
        "",
    ]

    # Domain table
    lines.append("| Domain | Count | Skills |")
    lines.append("|--------|-------|--------|")
    for domain in sorted(catalog["domains"]):
        skills = catalog["domains"][domain]
        lines.append(f"| {domain} | {len(skills)} | {', '.join(f'[{s}]`{s}`' for s in skills[:3])}{'...' if len(skills) > 3 else ''} |")
    lines.append("")

    # Parent-child families
    if catalog["parent_children"]:
        lines.append("## Parent-Child Families")
        lines.append("")
        for parent in sorted(catalog["parent_children"]):
            children = catalog["parent_children"][parent]
            lines.append(f"### `{parent}` ({len(children)} children)")
            lines.append("")
            for child in children:
                lines.append(f"- [`{child}`](#{child.replace('-', '')})")
            lines.append("")

    # Full skill listing
    lines.append("## All Skills (Alphabetical)")
    lines.append("")
    lines.append("| Skill | Domain | Parent | Epistemic | Description |")
    lines.append("|-------|--------|--------|-----------|-------------|")
    for entry in sorted(catalog["skills"], key=lambda e: e["name"]):
        desc = entry["description"][:80] + ("..." if len(entry["description"]) > 80 else "")
        parent = entry["parent_skill"] if entry["parent_skill"] != "none" else "—"
        lines.append(f"| [`{entry['name']}`](../{entry['path']}/SKILL.md) | {entry['domain']} | {parent} | {entry['epistemic_class']} | {desc} |")
    lines.append("")

    # Statistics
    lines.append("## Statistics")
    lines.append("")
    lines.append(f"- **Total skills**: {catalog['total_skills']}")
    lines.append(f"- **Total domains**: {catalog['total_domains']}")
    lines.append(f"- **Parent skills**: {catalog['total_parents']}")
    lines.append(f"- **Child skills**: {sum(len(c) for c in catalog['parent_children'].values())}")
    lines.append(f"- **Root skills (no parent)**: {catalog['total_skills'] - sum(len(c) for c in catalog['parent_children'].values())}")
    lines.append("")

    # Top domains by skill count
    lines.append("## Top Domains by Skill Count")
    lines.append("")
    domain_counts = [(d, len(catalog["domains"][d])) for d in catalog["domains"]]
    domain_counts.sort(key=lambda x: -x[1])
    lines.append("| Rank | Domain | Skills |")
    lines.append("|------|--------|--------|")
    for i, (domain, count) in enumerate(domain_counts[:15], 1):
        lines.append(f"| {i} | {domain} | {count} |")
    lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Auto-generate skill catalog from frontmatter")
    parser.add_argument("--skills-dir", default=".devin/skills", help="Skills directory")
    parser.add_argument("--output", default="skill-catalog.md", help="Output Markdown file")
    parser.add_argument("--json", default=None, help="Output JSON file")
    parser.add_argument("--summary", action="store_true", help="Print summary only")
    args = parser.parse_args()

    skills_dir = Path(args.skills_dir)
    catalog = build_catalog(skills_dir)

    if args.summary:
        print(f"Total skills:   {catalog['total_skills']}")
        print(f"Total domains:  {catalog['total_domains']}")
        print(f"Parent skills:  {catalog['total_parents']}")
        child_count = sum(len(c) for c in catalog["parent_children"].values())
        print(f"Child skills:   {child_count}")
        print(f"Root skills:    {catalog['total_skills'] - child_count}")
        return

    print("=" * 70)
    print("  AMOS Skill Catalog Generator")
    print("=" * 70)
    print()
    print(f"  Skills directory: {skills_dir}")
    print(f"  Total skills:     {catalog['total_skills']}")
    print(f"  Total domains:    {catalog['total_domains']}")
    print(f"  Parent skills:    {catalog['total_parents']}")
    child_count = sum(len(c) for c in catalog["parent_children"].values())
    print(f"  Child skills:     {child_count}")
    print(f"  Root skills:      {catalog['total_skills'] - child_count}")
    print()

    # Domain distribution
    print("  Domain distribution:")
    domain_counts = [(d, len(catalog["domains"][d])) for d in catalog["domains"]]
    domain_counts.sort(key=lambda x: -x[1])
    for domain, count in domain_counts[:15]:
        print(f"    {domain:30s} {count:4d} skills")
    if len(domain_counts) > 15:
        print(f"    ... and {len(domain_counts) - 15} more domains")
    print()

    # Top parent skills
    if catalog["parent_children"]:
        print("  Top parent skills:")
        parent_counts = [(p, len(c)) for p, c in catalog["parent_children"].items()]
        parent_counts.sort(key=lambda x: -x[1])
        for parent, count in parent_counts[:10]:
            print(f"    {parent:40s} {count:3d} children")
        print()

    # Generate Markdown
    markdown = generate_catalog_markdown(catalog, skills_dir)
    Path(args.output).write_text(markdown, encoding="utf-8")
    print(f"  Catalog written to: {args.output}")

    # Generate JSON
    if args.json:
        Path(args.json).write_text(
            json.dumps(catalog, indent=2, ensure_ascii=False), encoding="utf-8"
        )
        print(f"  JSON index written to: {args.json}")


if __name__ == "__main__":
    main()
