---
title: L09 Inference MOC
type: moc
source: 25_COGNITIVE_MATRIX/01_PRIMITIVES/L09_INFERENCE
tags:
- l09-inference
- domain/cognitive-matrix
- cognitive-matrix-l09-inference-contract
- l09-inference-primitives-cognitive-matrix-agents
- l09-inference-primitives-cognitive-matrix-hml
- l09-inference-primitives-cognitive-matrix-memory
- l09-inference-primitives-cognitive-matrix-purpose
- l09-inference-primitives-cognitive-matrix-readme
- l09-inference-primitives-cognitive-matrix-repair
- l09-inference-primitives-cognitive-matrix-rscf
- l09-inference-primitives-cognitive-matrix-skills
- l09-inference-primitives-cognitive-matrix-state
- l09-inference-primitives-cognitive-matrix-tests
moc: true
rscf:
  state: DERIVED
  claim_class: DERIVED
  provenance: AMOS_corpus
  scope: AMOS_general
---

# L09 Inference — Map of Content

**Path:** `25_COGNITIVE_MATRIX/01_PRIMITIVES/L09_INFERENCE`
**Files:** 23 | **Subdirectories:** 1

## Files

- [[COGNITIVE_MATRIX_L09_INFERENCE_CONTRACT]]
- [[L09_INFERENCE_PRIMITIVES_COGNITIVE_MATRIX_AGENTS]]
- [[L09_INFERENCE_PRIMITIVES_COGNITIVE_MATRIX_CONTROL_PLANES]]
- [[L09_INFERENCE_PRIMITIVES_COGNITIVE_MATRIX_DEFINITION]]
- [[L09_INFERENCE_PRIMITIVES_COGNITIVE_MATRIX_DEPENDENCIES]]
- [[L09_INFERENCE_PRIMITIVES_COGNITIVE_MATRIX_EQUATIONS]]
- [[L09_INFERENCE_PRIMITIVES_COGNITIVE_MATRIX_FAILURE_MODES]]
- [[L09_INFERENCE_PRIMITIVES_COGNITIVE_MATRIX_GAP_MATRIX]]
- [[L09_INFERENCE_PRIMITIVES_COGNITIVE_MATRIX_HML]]
- [[L09_INFERENCE_PRIMITIVES_COGNITIVE_MATRIX_INVARIANTS]]
- [[L09_INFERENCE_PRIMITIVES_COGNITIVE_MATRIX_MEMORY]]
- [[L09_INFERENCE_PRIMITIVES_COGNITIVE_MATRIX_OPERATORS]]
- [[L09_INFERENCE_PRIMITIVES_COGNITIVE_MATRIX_PROTOCOLS]]
- [[L09_INFERENCE_PRIMITIVES_COGNITIVE_MATRIX_PROVENANCE]]
- [[L09_INFERENCE_PRIMITIVES_COGNITIVE_MATRIX_PURPOSE]]
- [[L09_INFERENCE_PRIMITIVES_COGNITIVE_MATRIX_README]]
- [[L09_INFERENCE_PRIMITIVES_COGNITIVE_MATRIX_REPAIR]]
- [[L09_INFERENCE_PRIMITIVES_COGNITIVE_MATRIX_RSCF]]
- [[L09_INFERENCE_PRIMITIVES_COGNITIVE_MATRIX_SKILLS]]
- [[L09_INFERENCE_PRIMITIVES_COGNITIVE_MATRIX_STATE]]
- [[L09_INFERENCE_PRIMITIVES_COGNITIVE_MATRIX_TESTS]]
- [[L09_INFERENCE_PRIMITIVES_COGNITIVE_MATRIX_VARIABLES]]
- [[L09_INFERENCE_PRIMITIVES_COGNITIVE_MATRIX_WORKFLOWS]]

## Subdirectories

- [[00_INDEX_MOC]] — 00_INDEX

---
**Parent:** [[01_PRIMITIVES_MOC]]
